version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_ALLOWED_HOSTS=0.0.0.0,localhost

