# Generated by Django 5.2.1 on 2025-05-22 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DomainAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=255)),
                ("report", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                "verbose_name_plural": "Domain Analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
